#!/usr/bin/env python3
"""Make Pallet Town the whole game: remove every other map (tilesets are kept).

Kept: Pallet Town, all PalletTown_* interiors, and the link-cable rooms
(Battle Colosseums, Trade Center, Record Corner, Union Room) that the Pokémon
Center's upstairs uses. Everything else in data/maps and its layouts is deleted.

FireRed's engine still names many maps in its code (Safari Zone checks, Sevii
quests, fly points ...). Those constants are kept in a generated header with
dummy values that can never match a real map, so that code still compiles and
simply never runs. Heal locations keep their ids (tables are built from them);
the removed towns' ones point at Pallet so nothing can lead off the map.

Idempotent: reads the original lists from git, re-applies the same edits.
"""
import json
import os
import re
import shutil
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "pokefirered")


def p(*a):
    return os.path.join(ROOT, *a)


def git(path):
    return subprocess.run(["git", "-C", ROOT, "show", "HEAD:" + path], capture_output=True, check=True).stdout.decode()


def dump(o):
    return json.dumps(o, indent=2, ensure_ascii=False) + "\n"


def const_of(name):
    """Map folder name -> MAP_ constant, the way mapjson derives it from map.json."""
    try:
        return json.load(open(p("data/maps", name, "map.json")))["id"]
    except FileNotFoundError:
        return json.loads(git("data/maps/%s/map.json" % name))["id"]


orig_groups = json.loads(git("data/maps/map_groups.json"))
cur_groups = json.load(open(p("data/maps/map_groups.json")))
LINK = list(orig_groups["gMapGroup_Link"])
all_maps = [m for g in cur_groups["group_order"] for m in cur_groups[g]]
orig_maps = [m for g in orig_groups["group_order"] for m in orig_groups[g]]
keep = set(LINK) | {"PalletTown"} | {m for m in all_maps if m.startswith("PalletTown_")}

# ---- map groups: Link, the town, its interiors -------------------------------------
pallet_indoor = cur_groups.get("gMapGroup_IndoorPallet") or [m for m in all_maps if m.startswith("PalletTown_")]
groups = {"group_order": ["gMapGroup_Link", "gMapGroup_TownsAndRoutes", "gMapGroup_IndoorPallet"],
          "gMapGroup_Link": LINK, "gMapGroup_TownsAndRoutes": ["PalletTown"], "gMapGroup_IndoorPallet": pallet_indoor}
for k, v in cur_groups.items():   # keep any extra keys (e.g. connections_include_order)
    if not k.startswith("gMapGroup_") and k != "group_order":
        groups[k] = [m for m in v if m in keep] if isinstance(v, list) else v
open(p("data/maps/map_groups.json"), "w").write(dump(groups))

# ---- constants of removed maps: unique dummy values ----------------------------------
removed = [m for m in orig_maps if m not in keep]


def map_labels(m):
    out = []
    for f in ("scripts.inc", "text.inc"):
        try:
            out += re.findall(r"^(\w+)::", git("data/maps/%s/%s" % (m, f)), re.M)
        except subprocess.CalledProcessError:
            pass
    return out


# Some Pallet buildings reuse another map's scripts (the school's blackboard and notebook
# are Viridian School's). Those maps' scripts.inc/text.inc stay; only their map goes.
kept_tokens = set()
for m in keep:
    for f in ("map.json", "scripts.inc", "text.inc"):
        if os.path.exists(p("data/maps", m, f)):
            kept_tokens.update(re.findall(r"\w+", open(p("data/maps", m, f)).read()))
donors = sorted(m for m in removed if set(map_labels(m)) & kept_tokens)
for m in donors:
    os.makedirs(p("data/maps", m), exist_ok=True)
    for f in ("scripts.inc", "text.inc"):
        open(p("data/maps", m, f), "w").write(git("data/maps/%s/%s" % (m, f)))
removed_consts = []
for m in removed:
    try:
        removed_consts.append(const_of(m))
    except Exception:
        pass
lines = ["// Generated by pallet_upgrade/strip_maps.py: maps removed from this game.",
         "// Each keeps a unique value that is not a real map, so engine code that",
         "// mentions them still compiles and can never match. Group and number fit\n// in the s8 fields of a warp (0x40.. groups, numbers below 128).",
         "#ifndef GUARD_CONSTANTS_MAP_COMPAT_H", "#define GUARD_CONSTANTS_MAP_COMPAT_H", ""]
for i, c in enumerate(removed_consts):
    lines.append("#define %-48s (((0x40 + %d) << 8) | %d)" % (c, i // 128, i % 128))
lines += ["", "#endif", ""]
open(p("include/constants/map_compat.h"), "w").write("\n".join(lines))
maps_h = open(p("include/constants/maps.h")).read()
if "map_compat.h" not in maps_h:
    maps_h = maps_h.replace('#include "constants/map_types.h"\n',
                            '#include "constants/map_types.h"\n#include "constants/map_compat.h"\n')
    open(p("include/constants/maps.h"), "w").write(maps_h)

# ---- object local ids of removed maps (engine code names a few, e.g. the S.S. Anne) ------
kept_ids = set()
for m in keep:
    for o in json.load(open(p("data/maps", m, "map.json"))).get("object_events", []):
        kept_ids.add(o.get("local_id"))
lid = ["// Generated by pallet_upgrade/strip_maps.py: object ids of maps removed from this game.",
       "#ifndef GUARD_CONSTANTS_LOCALID_COMPAT_H", "#define GUARD_CONSTANTS_LOCALID_COMPAT_H", ""]
seen_ids = set()
for m in removed:
    try:
        objs = json.loads(git("data/maps/%s/map.json" % m)).get("object_events", [])
    except subprocess.CalledProcessError:
        continue
    for i, o in enumerate(objs):
        name = o.get("local_id")
        if name and name not in kept_ids and name not in seen_ids:
            seen_ids.add(name)
            lid.append("#define %-48s %d" % (name, i + 1))
lid += ["", "#endif", ""]
open(p("include/constants/localid_compat.h"), "w").write("\n".join(lid))
eo = open(p("include/constants/event_objects.h")).read()
if "localid_compat.h" not in eo:
    eo = eo.replace('#include "constants/map_event_ids.h"\n',
                    '#include "constants/map_event_ids.h"\n#include "constants/localid_compat.h"\n')
    open(p("include/constants/event_objects.h"), "w").write(eo)

# ---- layouts: only those the kept maps use ----------------------------------------------
used = {json.load(open(p("data/maps", m, "map.json")))["layout"] for m in keep}
used.add("LAYOUT_ROUTE1")   # Teachy TV's demo is drawn on Route 1
lay = json.load(open(p("data/layouts/layouts.json")))
orig_lay = json.loads(git("data/layouts/layouts.json"))
removed_layouts = [l for l in orig_lay["layouts"] if l.get("id") and l["id"] not in used]
lay["layouts"] = [l for l in lay["layouts"] if not l.get("id") or l["id"] in used]
open(p("data/layouts/layouts.json"), "w").write(dump(lay))
lcompat = ["// Generated by pallet_upgrade/strip_maps.py: layouts removed from this game.",
           "#ifndef GUARD_CONSTANTS_LAYOUT_COMPAT_H", "#define GUARD_CONSTANTS_LAYOUT_COMPAT_H", ""]
for i, l in enumerate(removed_layouts):
    lcompat.append("#define %-48s (0x7000 + %d)" % (l["id"], i))
lcompat += ["", "#endif", ""]
open(p("include/constants/layout_compat.h"), "w").write("\n".join(lcompat))
if "layout_compat.h" not in open(p("include/constants/maps.h")).read():
    s = open(p("include/constants/maps.h")).read()
    s = s.replace('#include "constants/map_compat.h"\n', '#include "constants/map_compat.h"\n#include "constants/layout_compat.h"\n')
    open(p("include/constants/maps.h"), "w").write(s)

for src in ("src/trainer_tower.c",):
    t = open(p(src)).read()
    if "layout_compat.h" not in t:
        t = t.replace('#include "constants/layouts.h"\n', '#include "constants/layouts.h"\n#include "constants/layout_compat.h"\n')
        open(p(src), "w").write(t)

# ---- map scripts and texts --------------------------------------------------------------
ev = open(p("data/event_scripts.s")).read()
def keep_line(line):
    m = re.search(r'"data/maps/([^/]+)/(scripts|text)\.inc"', line)
    return not m or m.group(1) in keep or m.group(1) in donors
ev = "".join(l for l in ev.splitlines(True) if keep_line(l))
open(p("data/event_scripts.s"), "w").write(ev)

# ---- stubs for labels of removed maps that shared code still names ----------------------
# (trainer tables, tutor texts, Pokédex habitats ...). Each becomes an alias of an empty
# script, text or movement; with the maps gone nothing can reach them.
labels = [l for m in removed if m not in donors for l in map_labels(m)]
tokens = set()
for top in ("src", "include", "data", "asm"):
    for dp, dn, fn in os.walk(p(top)):
        if os.path.basename(dp) in removed and os.path.basename(dp) not in donors:
            continue   # about to be deleted
        for f in fn:
            if f.endswith((".c", ".h", ".s", ".inc")) and f != "removed_maps.inc":
                tokens.update(re.findall(r"\w+", open(os.path.join(dp, f), errors="ignore").read()))
stubs = ["@ Generated by pallet_upgrade/strip_maps.py: labels of removed maps that shared",
         "@ scripts or engine code still name. All point at empty stand-ins.", "",
         "RemovedMap_Script::", "\tend", "RemovedMap_Text::", "\t.string \"$\"",
         "RemovedMap_Movement::", "\tstep_end", ""]
n_stub = 0
for l in sorted(set(labels)):
    if l in tokens:
        kind = "Movement" if "Movement" in l else "Text" if "Text" in l else "Script"
        stubs += ["\t.global %s" % l, "\t.set %s, RemovedMap_%s" % (l, kind)]
        n_stub += 1
open(p("data/maps/removed_maps.inc"), "w").write("\n".join(stubs) + "\n")
ev = open(p("data/event_scripts.s")).read()
if "removed_maps.inc" not in ev:
    ev = ev.rstrip("\n") + '\n\t.include "data/maps/removed_maps.inc"\n'
    open(p("data/event_scripts.s"), "w").write(ev)

# ---- wild encounters: only kept maps -----------------------------------------------------
we = json.load(open(p("src/data/wild_encounters.json")))
keep_consts = {const_of(m) for m in keep}
for grp in we["wild_encounter_groups"]:
    grp["encounters"] = [e for e in grp.get("encounters", []) if e.get("map") in keep_consts]
open(p("src/data/wild_encounters.json"), "w").write(dump(we))

# ---- heal locations: same ids; removed towns respawn at home -----------------------------
hl = json.load(open(p("src/data/heal_locations.json")))   # wire.py already moved Pallet's
for h in hl["heal_locations"]:
    if h.get("respawn_map") not in keep_consts or h.get("map") not in keep_consts:
        h["map"] = "MAP_PALLET_TOWN"
        h["x"], h["y"] = [e for e in hl["heal_locations"] if e["id"] == "HEAL_LOCATION_PALLET_TOWN"][0]["x"], \
                         [e for e in hl["heal_locations"] if e["id"] == "HEAL_LOCATION_PALLET_TOWN"][0]["y"]
        h["respawn_map"] = "MAP_PALLET_TOWN_PLAYERS_HOUSE_1F"
        h["respawn_npc"] = "LOCALID_MOM"
open(p("src/data/heal_locations.json"), "w").write(dump(hl))

# ---- Pallet Town no longer connects to Route 1 / Route 21 ----------------------------------
pt = json.load(open(p("data/maps/PalletTown/map.json")))
pt["connections"] = None
open(p("data/maps/PalletTown/map.json"), "w").write(dump(pt))

# ---- delete the removed maps and layouts --------------------------------------------------
gone_maps = 0
for m in removed:
    d = p("data/maps", m)
    if m in donors:
        for f in os.listdir(d):
            if f not in ("scripts.inc", "text.inc"):
                os.remove(os.path.join(d, f))
    elif os.path.isdir(d):
        shutil.rmtree(d)
        gone_maps += 1
used_dirs = {os.path.dirname(l["blockdata_filepath"]) for l in lay["layouts"] if l.get("id")} | \
            {os.path.dirname(l["border_filepath"]) for l in lay["layouts"] if l.get("id")}
gone_lay = 0
for l in removed_layouts:
    d = os.path.dirname(l["blockdata_filepath"])
    if d not in used_dirs and os.path.isdir(p(d)):
        shutil.rmtree(p(d))
        gone_lay += 1
print("strip: %d stub labels; scripts kept from %s" % (n_stub, ", ".join(donors) or "no removed map"))
print("strip: kept %d maps, removed %d maps (%d folders now) and %d layouts" %
      (len(keep), len(removed), gone_maps, len(removed_layouts)))
